# Домашнее задание "Продвинутая линейная алгебра".

Уровень 0:
Придумайте матрицы, которые обладают следующими свойствами:

a) Диагональная, ортогональная, но не единичная(!)

b) Верхнетреугольная, ортогональная

c) Нижнетреугольная, ортогональная

d) Матрица, у которой определитель = 1, и все элементы не равны 0

P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!

Найдите собственные значения и собственные вектора матриц:

m = np.array([[2, 2],
              [1, 3]])
print(m)

In [70]:
import numpy as np
from scipy import linalg

a) Диагональная, ортогональная, но не единичная(!)

In [8]:
A = np.array([[0, -1, 0],
                [1, 0, 0],
                [0, 0, -1]])
A

array([[ 0, -1,  0],
       [ 1,  0,  0],
       [ 0,  0, -1]])

In [2]:
inv_A = linalg.inv(A)
print(inv_A)

NameError: name 'linalg' is not defined

In [9]:
A@A.T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

b) Верхнетреугольная, ортогональная

In [19]:
B = np.triu(A, 0)
B

array([[ 0, -1,  0],
       [ 0,  0,  0],
       [ 0,  0, -1]])

In [20]:
B@B.T

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 1]])

In [75]:
B1 = np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 0)
print(B1)

[[1 2 3]
 [0 5 6]
 [0 0 9]
 [0 0 0]]


c) Нижнетреугольная, ортогональная

In [23]:
C = np.tril(A, 0)
C

array([[ 0,  0,  0],
       [ 1,  0,  0],
       [ 0,  0, -1]])

In [77]:
C1 = np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
print(C1)

[[ 0  0  0]
 [ 4  0  0]
 [ 7  8  0]
 [10 11 12]]


d) Матрица, у которой определитель = 1, и все элементы не равны 0

In [32]:
D = np.array([[2, 3, 6], [1, 1, 4], [1, 2, 1]], dtype=np.float32)
det = np.linalg.det(D)
print(D)
print(det)

[[2. 3. 6.]
 [1. 1. 4.]
 [1. 2. 1.]]
1.0


Найдите собственные значения и собственные вектора матриц:

In [33]:
a = np.array([[2, 2],
              [1, 3]])
print(a)

[[2 2]
 [1 3]]


In [37]:
x, x1 = np.linalg.eig(a)

In [38]:
x # собственные значения

array([1., 4.])

In [40]:
x1 #собственные вектора матрицы

array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]])

# Уровень 1:

Найдите спектральное разложение матрицы:

In [67]:
m = np.array([[1, 2],
              [2,3]])
print(m)

[[1 2]
 [2 3]]


Спектральное разложение матрицы:

m = St D S,где

S - ортогональная,
D - диагональная из собственных значений X.

In [68]:
# собственне значения матрицы
w,v = linalg.eig(m)
np.array(w)

array([-0.23606798+0.j,  4.23606798+0.j])

In [69]:
D = np.diag(w)
D

array([[-0.23606798+0.j,  0.        +0.j],
       [ 0.        +0.j,  4.23606798+0.j]])

In [53]:
S = v.T
S

array([[-0.85065081,  0.52573111],
       [-0.52573111, -0.85065081]])

In [54]:
St = S.transpose()
St

array([[-0.85065081, -0.52573111],
       [ 0.52573111, -0.85065081]])

In [59]:
print(St @ D @ S)


[[1.+0.j 2.+0.j]
 [2.+0.j 3.+0.j]]


In [64]:
print(np.array(v.dot(np.diag(w)).dot(v.T), dtype = float))

[[1. 2.]
 [2. 3.]]


<ipython-input-64-e80c8c6c9757>:1: ComplexWarning: Casting complex values to real discards the imaginary part
  print(np.array(v.dot(np.diag(w)).dot(v.T), dtype = float))
